
version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn selteq_task.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
